
package cl.akzio.auth.central.obtenercapacidadfabrica.service;

import java.io.Serializable;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * @author Marcel Aedo (Akzio Consultores S.A.) en nombre de Daniela Cruz(Akzio Consultores S.A.)
 * @since 10-01-2018
 * @version 1.0
 */
@WebServiceClient(name = "ObtenerCapacidadFabrica", targetNamespace = "http://www.akzio.cl/auth/central/t/obtenercapacidadfabrica/", wsdlLocation = "WEB-INF/wsdl/ObtenerCapacidadFabrica.wsdl")
public class ObtenerCapacidadFabrica extends Service implements Serializable{

    /**
	 * Atributo serialVersionUID long
	 */
	private static final long serialVersionUID = -3159161961297098493L;
	private final static URL OBTENERCAPACIDADFABRICA_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(cl.akzio.auth.central.obtenercapacidadfabrica.service.ObtenerCapacidadFabrica.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = cl.akzio.auth.central.obtenercapacidadfabrica.service.ObtenerCapacidadFabrica.class.getResource(".");
            url = new URL(baseUrl, "WEB-INF/wsdl/ObtenerCapacidadFabrica.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'WEB-INF/wsdl/ObtenerCapacidadFabrica.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        OBTENERCAPACIDADFABRICA_WSDL_LOCATION = url;
    }

    public ObtenerCapacidadFabrica(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ObtenerCapacidadFabrica() {
        super(OBTENERCAPACIDADFABRICA_WSDL_LOCATION, new QName("http://www.akzio.cl/auth/central/t/obtenercapacidadfabrica/", "ObtenerCapacidadFabrica"));
    }

    /**
     * 
     * @return
     *     returns ObtenerCapacidadFabricaPortType
     */
    @WebEndpoint(name = "ObtenerCapacidadFabricaPort")
    public ObtenerCapacidadFabricaPortType getObtenerCapacidadFabricaPort() {
        return super.getPort(new QName("http://www.akzio.cl/auth/central/t/obtenercapacidadfabrica/", "ObtenerCapacidadFabricaPort"), ObtenerCapacidadFabricaPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ObtenerCapacidadFabricaPortType
     */
    @WebEndpoint(name = "ObtenerCapacidadFabricaPort")
    public ObtenerCapacidadFabricaPortType getObtenerCapacidadFabricaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.akzio.cl/auth/central/t/obtenercapacidadfabrica/", "ObtenerCapacidadFabricaPort"), ObtenerCapacidadFabricaPortType.class, features);
    }

	/**
	 * @return the obtenercapacidadfabricaWsdlLocation
	 */
	public static URL getObtenercapacidadfabricaWsdlLocation() {
		return OBTENERCAPACIDADFABRICA_WSDL_LOCATION;
	}

	/**
	 * @return the logger
	 */
	public static Logger getLogger() {
		return logger;
	}

}
