/* Propiedad de Akzio Fabrica Temuco. Todos los derechos reservados */
package cl.akzio.auth.central.obtenercapacidadfabrica.service;

import java.io.Serializable;

import javax.xml.ws.WebFault;

import cl.akzio.auth.central.obtenercapacidadfabrica.types.fault.ObtenerCapacidadFabricaFaultType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * @author Marcel Aedo (Akzio Consultores S.A.) en nombre de Daniela Cruz(Akzio Consultores S.A.)
 * @since 10-01-2018
 * @version 1.0
 */
@WebFault(name = "obtenerCapacidadFabricaFaultDocument", targetNamespace = "http://www.akzio.cl/auth/central/t/obtenercapacidadfabrica/fault")
public class ObtenerCapacidadFabricaFaultMessage extends Exception implements Serializable{

    /**
	 * Atributo serialVersionUID long
	 */
	private static final long serialVersionUID = 8859380516047708344L;
	public void setFaultInfo(ObtenerCapacidadFabricaFaultType faultInfo) {
		this.faultInfo = faultInfo;
	}

	public ObtenerCapacidadFabricaFaultMessage() {
		super();
	}

	public ObtenerCapacidadFabricaFaultMessage(
			ObtenerCapacidadFabricaFaultType faultInfo) {
		super();
		this.faultInfo = faultInfo;
	}

	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ObtenerCapacidadFabricaFaultType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ObtenerCapacidadFabricaFaultMessage(String message, ObtenerCapacidadFabricaFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ObtenerCapacidadFabricaFaultMessage(String message, ObtenerCapacidadFabricaFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: cl.akzio.auth.central.t.obtenercapacidadfabrica.fault.ObtenerCapacidadFabricaFaultType
     */
    public ObtenerCapacidadFabricaFaultType getFaultInfo() {
        return faultInfo;
    }

}
